
variables:
  nightlyDefines: 'DEFINES+=NIGHTLY=$(Build.BuildNumber)'
  nightlyString: '-nightly'

name: '$(Date:yyyy-MM-dd).$(Rev:r)'
jobs:
- job: Build

  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-16.04'
      macos:
        imageName: 'macOS-10.15'
      win64:
        imageName: 'windows-2019'
        qtArch: 'win64_msvc2017_64'
      win32:
        imageName: 'windows-2019'
        qtArch: 'win32_msvc2017'
      qt59:
        imageName: 'ubuntu-18.04'
        dontPublish: 'true'
        skipDeploy: 'true'

  pool:
    vmImage: $(imageName)

  steps:
  - bash: echo '##vso[task.setvariable variable=MatrixName]'$(echo $(Agent.JobName) | cut -d' ' -f2)
    condition: and(succeeded(), ne(variables['dontPublish'], 'true'))
    displayName: 'Set matrix name'

  - checkout: self

  - template: ci/install-qt.yml
    parameters:
      arch: $(qtArch)

  - template: ci/build.yml
    parameters:
      defines: $(nightlyDefines)
      arch: $(qtArch)
    
  - template: ci/plugins.yml

  - template: ci/deploy.yml
    parameters:
      skipDeploy: $(skipDeploy)
      extraPlugins: 'imageformats/libqapng.so,imageformats/libqavif.so,imageformats/libqheif.so'


  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'bin'
      artifactName: 'qView$(nightlyString)-$(MatrixName).$(Build.BuildNumber)'
    condition: and(succeeded(), ne(variables['dontPublish'], 'true'))
    displayName: 'Publish build artifact'

