steps:
- script: |
    call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars%arch:~3,2%.bat"
    qmake $[nightlyDefines]
    nmake
  condition: and(succeeded(), eq( variables['Agent.OS'], 'Windows_NT' ))
  displayName: 'Build qView (Windows)'

- script: |
    qmake $[nightlyDefines]
    make
  condition: and(succeeded(), ne( variables['Agent.OS'], 'Windows_NT' ))
  displayName: 'Build qView (Unix)'